paths:
  /routing/endpoints:
    get:
      tags:
        - routing
      summary: Show all available communication endpoints
      operationId: readEnpoints
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  anyOf:
                  - $ref: "#/components/schemas/networkEndpoint"
                  - $ref: "#/components/schemas/serialEndpoint"
        500:
          description: Failed to list the endpoints
    post:
      tags:
        - routing
      summary: Create new endpoint.
      operationId: newEndpoint
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/networkEndpoint'
                - $ref: '#/components/schemas/serialEndpoint'
              $ref: "#/components/schemas/endpoint"
      responses:
        200:
          description: Endpoint created
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                  - $ref: "#/components/schemas/networkEndpoint"
                  - $ref: "#/components/schemas/serialEndpoint"
        500:
          description: Failed to create endpoint
    delete:
      tags:
        - routing
      summary: Delete an Endpoint
      operationId: deleteEndpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                endpointId:
                  type: integer
                  example: 0
      responses:
        200:
          description: Endpoint deleted successfully
        500:
          description: Failed to delete endpoint
          content:
            text/plain:
              schema:
                type: string
                example: "Error: Endpoint is still linked"

  /routing/links:
    get:
      tags:
        - routing
      summary: Show all existent endpoint links
      operationId: readLinks
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/link"
        500:
          description: Failed to list links
    post:
      tags:
        - routing
      summary: Create new link
      operationId: newLink
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/link"
      responses:
        200:
          description: Link created successfully
        500:
          description: Error while creating link
    delete:
      tags:
        - routing
      summary: Delete a link
      operationId: deleteLink
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
              properties:
                linkId:
                  type: integer
                  example: 0
      responses:
        200:
          description: Link deleted successfully
        500:
          description: Failed to delete link
          content:
            text/plain:
              schema:
                type: string
                example: Failed to delete link (reason here)

components:
  schemas:
    networkEndpoint:
      type: object
      properties:
        id:
          type: integer
          example: 1
          readOnly: true
        ip:
          type: string
          example: 0.0.0.0
        port:
          type: integer
          example: 12345
        role:
          type: string
          enum: [client, server]
        protocol:
          type: string
          enum: [udp, tcp]
        name:
          type: string
          example: Arduino UDP Relay

    serialEndpoint:
      type: object
      properties:
        id:
          type: integer
          example: 2
          readOnly: true
        devicePath:
          type: string
          example: /dev/ttyUSB0
        baudrate:
          type: integer
          example: 115200
        name:
          type: string
          example: Arduino Uno

    link:
      type: object
      properties:
        id:
          type: number
          example: 0
          readOnly: true
        from_id:
          type: integer
          example: 1
        to_id:
          type: integer
          example: 3
        throughput_in_bps:
          type: number
          example: 123.45
          readOnly: true
        throughput_out_bps:
          type: number
          example: 123.45
          readOnly: true
